=== ZocoLini/mk-template/crates/txml_processor/txml_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Variable" type="variableType" minOccurs="0" maxOccurs="unbounded"/>

                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="File" type="fileType" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="Directory" type="directoryType" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>

            <xs:attribute name="renamable" type="xs:boolean" default="true"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="variableType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="fileType">
        <xs:complexContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
                <xs:attribute name="extension" type="xs:string"/>
                <xs:attribute name="command" type="xs:string" default=""/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="directoryType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="File" type="fileType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Directory" type="directoryType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="in_command" type="xs:string" default=""/>
        <xs:attribute name="out_command" type="xs:string" default=""/>
    </xs:complexType>

    <xs:simpleType name="fileNameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_\-.]+"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ZocoLini/mk-template/tests/resources/template_example_1.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="https://lebastudios.org/xml-schemas/txml_schema.xsd">
    <Directory name="crates" in_command="git init   ;      mkdir pepe">
        <File name="Hola" extension="rs">
            fn main()
            {
                println!("Hola, mundo!");
            }
        </File>
        <Directory name="crate">
            <File name="sin_titulo" extension="txt">
                Hola me llamo Juan
                Pepe
            </File>
        </Directory>
    </Directory>

    <File name="Cargo" extension="toml">
        [workspace]
        resolver = "2"
        members = []
    </File>
    <File name="rustfmt" extension="toml"/>
    <File name=".gitignore"/>
</Root>
